### ISSUE TITLE
Unable to create desktop entry on Ubuntu 20.04

### ISSUE THREAD

**Issue by Sciroccogti** [pineappleEA/Pineapple-Linux#16] opened 2021-01-02 11:57 UTC
```Bash
Compilation completed, do you wish to install it systemwide [y/n]?:y
Could not parse file "/usr/share/applications/yuzu.desktop": Key file does not have group ?Desktop Entry?
Installation completed. Use the command yuzu or run it from your launcher.
```

Though it's able to use command `yuzu` to start, desktop entry is missing.

~~It seems that the file `/usr/share/applications/yuzu.desktop` exists but is empty. I tried to remove it with sudo and reinstall yuzu but in vain.~~

~~However, when I copied the lines in `https://raw.githubusercontent.com/pineappleEA/Pineapple-Linux/master/yuzu.desktop` to the local file with sudo, it works! (though no icon appeared)~~

I noticed that files downloaded with `sudo sh -c "curl -s"` are all empty... But if I use `sh -c "curl -s"`, then the files are all right. I don't know if it is only occurred in China, since `https://raw.githubusercontent.com` can only be accessed with proxy here.

**Comment by MGThePro** [comment] 2021-01-02 13:12
So far I have not managed to reproduce this issue anywhere. To me it sounds like your proxy is being used only on your user, so anything ran on sudo will try to connect without that proxy.
You should be able to find it out by running 
`sh -c "dig +short myip.opendns.com @resolver1.opendns.com"` 
with and without sudo. The command should output your public IP that is exposed to opendns.com. If it outputs two different IP addresses my assumption is probably correct.
 I don't know if opendns works in China, but if it doesn't there is probably some alternative service that does the same thing.

**Comment by Sciroccogti** [comment] 2021-01-02 13:26
The two IPs are the same... but I don't think it's an issue of pineappleEA, so I am closing it. Thank you for your advice!

**Comment by edisionnano** [comment] 2021-01-03 17:23
Other than https://raw.githubusercontent.com, are any other github domains blocked there, cause we can easily solve the issue.

**Comment by Sciroccogti** [comment] 2021-01-04 13:19
> Other than https://raw.githubusercontent.com, are any other github domains blocked there, cause we can easily solve the issue.

Seems no more domains. But I don't think it's necessary to change the url just for these blocked regions😄

**Comment by edisionnano** [comment] 2021-01-04 18:01
> > Other than https://raw.githubusercontent.com, are any other github domains blocked there, cause we can easily solve the issue.
> 
> Seems no more domains. But I don't think it's necessary to change the url just for these blocked regionssmile

We want the script to work everywhere and its an easy change having a fallback, we now added translations including Chinese. Can you confirm me that https://pineappleea.github.io/ is accessible?

**Comment by edisionnano** [comment] 2021-01-05 02:52
Well, anyways. Try this script and tell me if it works 

https://gist.github.com/edisionnano/57f92333f7df361b1c039e4cbb51ccb4

Turns out all subdomains of githubusercontent.com are blocked in Mainland Chine (including gist,diff etc)

**Comment by Sciroccogti** [comment] 2021-01-05 15:19
> Well, anyways. Try this script and tell me if it works
> 
> https://gist.github.com/edisionnano/57f92333f7df361b1c039e4cbb51ccb4
> 
> Turns out all subdomains of githubusercontent.com are blocked in Mainland Chine (including gist,diff etc)

Thank you very much! The new lines does work! I tried both the current script in repo and the script from gist, and the former one still won't work while the latter one is perfect.

**Comment by edisionnano** [comment] 2021-01-10 16:33
I committed, can you check the normal script and tell me whether it works or not so I can close the issue.

**Comment by Sciroccogti** [comment] 2021-01-12 14:27
After correcting [this typo](https://github.com/pineappleEA/Pineapple-Linux/commit/48e6b3b706c863ec3e23541f609e5b1cd20c5caa#r45882268), it works well!

**Closed** 2021-01-12 20:53 UTC
